apiVersion: apps/v1
kind: Deployment
metadata:
  name: foodhub-api
  labels:
    app: foodhub-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foodhub-api
  template:
    metadata:
      labels:
        app: foodhub-api
    spec:
      containers:
      - name: foodhub-api
        image: foodhub-api:latest
        imagePullPolicy: Never   # local Docker Desktop image
        ports:
        - containerPort: 8080
          name: http

        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"

        - name: ASPNETCORE_URLS
          value: "http://+:8080"


        # 🔐 Local Key Vault auth (same as docker run)
        - name: AZURE_CLIENT_ID
          value: "AZURE_CLIENT_ID"

        - name: AZURE_CLIENT_SECRET
          value: "AZURE_CLIENT_SECRET"

        - name: AZURE_TENANT_ID
          value: "AZURE_TENANT_ID"

        - name: KeyVaultUrl
          value: "KeyVaultUrl"

        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"

        livenessProbe:
          httpGet:
            path: /graphql
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10

        readinessProbe:
          httpGet:
            path: /graphql
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 5
