apiVersion: v1
kind: Service
metadata:
  name: foodhub-api
  labels:
    app: foodhub-api
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080  # Fixed port for local access
    protocol: TCP
    name: http
  selector:
    app: foodhub-api
